replicaCount: 1
namespace: stage

configmap:
  enable: false

deployment: {}

image:
  repository: docker-registry.ad.tt.se/ttab/sunk
  tag: latest
  pullPolicy: IfNotPresent
  env:
    - name: CONF
      value: conf-prod.json

resources:
  requests:
    memory: 
  limits:
    memory: 

pvc:
  enable: false
  size: 
  accessModes:
    - ReadWriteOnce

service:
  enabled: false
  name: 
  ports:
    - name:
      port: 
      targetPort: 

ingress:
  enabled: false
  hosts: []

