apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "ttservice.deployname" . }}
  namespace: {{ .Values.namespace }}
{{- if .Values.deployment.metadata }}
{{ toYaml .Values.deployment.metadata | indent 2 -}}
{{- end }}
{{- if .Values.deployment.annotations }}
  annotations:
{{ toYaml .Values.deployment.annotations | indent 4 -}}
{{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  {{- if .Values.deployment.strategy }}
  strategy:
{{ toYaml .Values.deployment.strategy | indent 4 -}}
{{- end }}
  selector:
    matchLabels:
      app: {{ template "ttservice.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "ttservice.name" . }}
    spec:
      containers:
        - name: {{ template "ttservice.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.image.env }}
          env:
{{ toYaml .Values.image.env | indent 12 -}}
          {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 -}}

