{{- if .Values.pvc.enable }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "ttservice.pvcname" . }}
  namespace: {{ .Values.namespace }}
{{- if .Values.pvc.metadata }}
{{ toYaml .Values.pvc.metadata | indent 2 -}}
{{- end }}
{{- if .Values.pvc.annotations }}
  annotations:
{{ toYaml .Values.pvc.annotations | indent 4 -}}
{{- end }}
{{- if .Values.pvc.labels }}
  labels:
{{ toYaml .Values.pvc.labels | indent 4 -}}
{{- end }}
spec:
  accessModes:
{{ toYaml .Values.pvc.accessModes | indent 4 }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
status: {}
{{ end }}
