---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: tapiren
  namespace: default
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: tapiren
  chart:
    git: ssh://git@github.com:ttab/flux-get-started.git
    ref: master
    path: charts/tapiren
  values:
    image:
      repository: docker-registry.ad.tt.se/ttab/tapiren
      tag: latest
      env:
        - name: CONF
          value: conf-prod.json
    resources:
      requests:
        memory: 40Mi
      limits:
        memory: 80Mi

    service:
      enabled: true
      ports:
        - name: http
          port: 3333
          targetPort: 3333
    ingress:
      enabled: true
      hosts:
        - adm.tt.se/tapiren
        - traefik.tt.se/tapiren
